#**1. Business Understanding**

###**1.1 Business Background**
Superstore merupakan perusahaan retail yang menjual berbagai kategori produk kepada pelanggan individu, perusahaan, maupun home office. Perusahaan memiliki banyak transaksi penjualan setiap hari sehingga menghasilkan data yang dapat dimanfaatkan untuk mengevaluasi performa bisnis. Agar perusahaan dapat mengambil keputusan yang lebih tepat, diperlukan analisis terhadap data penjualan untuk mengetahui performa penjualan, keuntungan, perilaku pelanggan, serta kategori produk yang memberikan kontribusi terbesar terhadap bisnis.

### **1.2 Business Problem**

Manajemen belum memiliki gambaran yang jelas mengenai performa penjualan dan profit di setiap
wilayah, kategori produk, serta segmen pelanggan. Tanpa analisis yang tepat, perusahaan akan
kesulitan menentukan strategi bisnis untuk meningkatkan pendapatan dan keuntungan.

### **1.3 Business Objectives**

- Menganalisis performa penjualan perusahaan.
- Mengidentifikasi kategori produk dengan performa terbaik.
- Mengetahui wilayah dengan penjualan dan profit tertinggi.
- Mengidentifikasi pelanggan dengan kontribusi terbesar.
- Memberikan rekomendasi bisnis berdasarkan hasil analisis.

### **1.4 Business Questions**

**Sales Performance**
1. Berapa total Sales yang dihasilkan perusahaan?
2. Berapa total Profit yang diperoleh perusahaan?
3. Bagaimana tren Sales dari waktu ke waktu?

**Product Analysis**

4. Kategori produk apa yang menghasilkan Sales terbesar?
5. Sub-category apa yang menghasilkan Profit terbesar?

**Customer Analysis**

6. Segmen pelanggan mana yang paling menguntungkan?
7. Siapa customer dengan kontribusi Sales terbesar?

**Regional Analysis**

8. Region mana yang menghasilkan Sales terbesar?
9. State mana yang memiliki Profit terendah?

**Discount Analysis**

10. Apakah Discount yang tinggi memengaruhi Profit?

### **1.5 Success Metrics**

Project dianggap berhasil apabila mampu:
1. Menghasilkan proses data cleaning yang baik.
2. Menyajikan analisis menggunakan Python, SQL, dan Power BI.
3. Menjawab seluruh business questions.
4. Memberikan rekomendasi bisnis yang dapat ditindaklanjuti.

# **2. Data Understanding**

####**2.1 Import & load data**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Career Journey/Portofolio/1. retail sales analysis/data/raw/Sample - Superstore.csv', encoding='latin1')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

####**2.2 Shape Data set**

In [ ]:
print(f"Jumlah baris: {df.shape[0]}")
print(f"Jumlah kolom: {df.shape[1]}")

Jumlah baris: 9994
Jumlah kolom: 21

####**2.3 Data Types**

In [ ]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

####**2.4 Cek missing values**

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

####**2.5 Cek Duplicate Value**

In [ ]:
print(f"Jumlah baris duplikat: {df.duplicated().sum()}")

Jumlah baris duplikat: 0

####**2.6 Statistical Summary**

In [ ]:
df.describe(include='number')

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [ ]:
df.describe(include='object')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,1237,1334,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2017-100111,9/5/2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,35,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48